package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditTrails generated by hbm2java
 */
public class AuditTrails  implements java.io.Serializable {


     private int id;
     private Users users;
     private String action;
     private Date actionDate;
     private Integer orgId;

    public AuditTrails() {
    }

	
    public AuditTrails(int id, Users users, Date actionDate) {
        this.id = id;
        this.users = users;
        this.actionDate = actionDate;
    }
    public AuditTrails(int id, Users users, String action, Date actionDate, Integer orgId) {
       this.id = id;
       this.users = users;
       this.action = action;
       this.actionDate = actionDate;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


