package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BudgetPhases generated by hbm2java
 */
public class BudgetPhases  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private Set budgetTimetableActivitieses = new HashSet(0);

    public BudgetPhases() {
    }

	
    public BudgetPhases(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public BudgetPhases(int id, String name, Date dateCreated, Integer orgId, Set budgetTimetableActivitieses) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.budgetTimetableActivitieses = budgetTimetableActivitieses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getBudgetTimetableActivitieses() {
        return this.budgetTimetableActivitieses;
    }
    
    public void setBudgetTimetableActivitieses(Set budgetTimetableActivitieses) {
        this.budgetTimetableActivitieses = budgetTimetableActivitieses;
    }




}


