package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BudgetPerformanceReview generated by hbm2java
 */
public class BudgetPerformanceReview  implements java.io.Serializable {


     private int id;
     private BudgetYears budgetYears;
     private PerformanceGrades performanceGrades;
     private double budgetedValue;
     private Double expendedValue;
     private double committedValue;
     private double varianceValue;
     private Integer mdaId;
     private Date dateCreated;
     private Integer orgId;

    public BudgetPerformanceReview() {
    }

	
    public BudgetPerformanceReview(int id, BudgetYears budgetYears, PerformanceGrades performanceGrades, double budgetedValue, double committedValue, double varianceValue, Date dateCreated) {
        this.id = id;
        this.budgetYears = budgetYears;
        this.performanceGrades = performanceGrades;
        this.budgetedValue = budgetedValue;
        this.committedValue = committedValue;
        this.varianceValue = varianceValue;
        this.dateCreated = dateCreated;
    }
    public BudgetPerformanceReview(int id, BudgetYears budgetYears, PerformanceGrades performanceGrades, double budgetedValue, Double expendedValue, double committedValue, double varianceValue, Integer mdaId, Date dateCreated, Integer orgId) {
       this.id = id;
       this.budgetYears = budgetYears;
       this.performanceGrades = performanceGrades;
       this.budgetedValue = budgetedValue;
       this.expendedValue = expendedValue;
       this.committedValue = committedValue;
       this.varianceValue = varianceValue;
       this.mdaId = mdaId;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public PerformanceGrades getPerformanceGrades() {
        return this.performanceGrades;
    }
    
    public void setPerformanceGrades(PerformanceGrades performanceGrades) {
        this.performanceGrades = performanceGrades;
    }
    public double getBudgetedValue() {
        return this.budgetedValue;
    }
    
    public void setBudgetedValue(double budgetedValue) {
        this.budgetedValue = budgetedValue;
    }
    public Double getExpendedValue() {
        return this.expendedValue;
    }
    
    public void setExpendedValue(Double expendedValue) {
        this.expendedValue = expendedValue;
    }
    public double getCommittedValue() {
        return this.committedValue;
    }
    
    public void setCommittedValue(double committedValue) {
        this.committedValue = committedValue;
    }
    public double getVarianceValue() {
        return this.varianceValue;
    }
    
    public void setVarianceValue(double varianceValue) {
        this.varianceValue = varianceValue;
    }
    public Integer getMdaId() {
        return this.mdaId;
    }
    
    public void setMdaId(Integer mdaId) {
        this.mdaId = mdaId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


