package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BudgetVersionStatus generated by hbm2java
 */
public class BudgetVersionStatus  implements java.io.Serializable {


     private int id;
     private BudgetStatus budgetStatus;
     private BudgetVersions budgetVersions;
     private BudgetYears budgetYears;
     private Date dateCreated;
     private Integer orgId;

    public BudgetVersionStatus() {
    }

	
    public BudgetVersionStatus(int id, BudgetStatus budgetStatus, BudgetVersions budgetVersions, BudgetYears budgetYears, Date dateCreated) {
        this.id = id;
        this.budgetStatus = budgetStatus;
        this.budgetVersions = budgetVersions;
        this.budgetYears = budgetYears;
        this.dateCreated = dateCreated;
    }
    public BudgetVersionStatus(int id, BudgetStatus budgetStatus, BudgetVersions budgetVersions, BudgetYears budgetYears, Date dateCreated, Integer orgId) {
       this.id = id;
       this.budgetStatus = budgetStatus;
       this.budgetVersions = budgetVersions;
       this.budgetYears = budgetYears;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetStatus getBudgetStatus() {
        return this.budgetStatus;
    }
    
    public void setBudgetStatus(BudgetStatus budgetStatus) {
        this.budgetStatus = budgetStatus;
    }
    public BudgetVersions getBudgetVersions() {
        return this.budgetVersions;
    }
    
    public void setBudgetVersions(BudgetVersions budgetVersions) {
        this.budgetVersions = budgetVersions;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


