package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BudgetTimetableActivities generated by hbm2java
 */
public class BudgetTimetableActivities  implements java.io.Serializable {


     private int id;
     private BudgetPhases budgetPhases;
     private BudgetTimetable budgetTimetable;
     private String name;
     private String description;
     private Date fromDate;
     private Date toDate;
     private Date dateCreated;
     private Integer orgId;
     private Set meetingDetailses = new HashSet(0);

    public BudgetTimetableActivities() {
    }

	
    public BudgetTimetableActivities(int id, BudgetTimetable budgetTimetable, String name, String description, Date fromDate, Date toDate, Date dateCreated) {
        this.id = id;
        this.budgetTimetable = budgetTimetable;
        this.name = name;
        this.description = description;
        this.fromDate = fromDate;
        this.toDate = toDate;
        this.dateCreated = dateCreated;
    }
    public BudgetTimetableActivities(int id, BudgetPhases budgetPhases, BudgetTimetable budgetTimetable, String name, String description, Date fromDate, Date toDate, Date dateCreated, Integer orgId, Set meetingDetailses) {
       this.id = id;
       this.budgetPhases = budgetPhases;
       this.budgetTimetable = budgetTimetable;
       this.name = name;
       this.description = description;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.meetingDetailses = meetingDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetPhases getBudgetPhases() {
        return this.budgetPhases;
    }
    
    public void setBudgetPhases(BudgetPhases budgetPhases) {
        this.budgetPhases = budgetPhases;
    }
    public BudgetTimetable getBudgetTimetable() {
        return this.budgetTimetable;
    }
    
    public void setBudgetTimetable(BudgetTimetable budgetTimetable) {
        this.budgetTimetable = budgetTimetable;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getMeetingDetailses() {
        return this.meetingDetailses;
    }
    
    public void setMeetingDetailses(Set meetingDetailses) {
        this.meetingDetailses = meetingDetailses;
    }




}


