package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BudgetReport generated by hbm2java
 */
public class BudgetReport  implements java.io.Serializable {


     private int Id;
     private String ReportTitle;
     private String ReportText;
     private Integer BudgetYear;
     private Date ReportDate;

    public BudgetReport() {
    }

	
    public BudgetReport(int Id, Date ReportDate) {
        this.Id = Id;
        this.ReportDate = ReportDate;
    }
    public BudgetReport(int Id, String ReportTitle, String ReportText, Integer BudgetYear, Date ReportDate) {
       this.Id = Id;
       this.ReportTitle = ReportTitle;
       this.ReportText = ReportText;
       this.BudgetYear = BudgetYear;
       this.ReportDate = ReportDate;
    }
   
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }
    public String getReportTitle() {
        return this.ReportTitle;
    }
    
    public void setReportTitle(String ReportTitle) {
        this.ReportTitle = ReportTitle;
    }
    public String getReportText() {
        return this.ReportText;
    }
    
    public void setReportText(String ReportText) {
        this.ReportText = ReportText;
    }
    public Integer getBudgetYear() {
        return this.BudgetYear;
    }
    
    public void setBudgetYear(Integer BudgetYear) {
        this.BudgetYear = BudgetYear;
    }
    public Date getReportDate() {
        return this.ReportDate;
    }
    
    public void setReportDate(Date ReportDate) {
        this.ReportDate = ReportDate;
    }




}


