package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BudgetYears generated by hbm2java
 */
public class BudgetYears  implements java.io.Serializable {


     private int id;
     private String name;
     private int year;
     private boolean isCurrentBaseYear;
     private Date dateCreated;
     private int orgId;
     private Set mtefDepartmentFigureses = new HashSet(0);
     private Set mybfFigureses = new HashSet(0);
     private Set mtssSubSectorCeilings = new HashSet(0);
     private Set mtssSectorCeilings = new HashSet(0);
     private Set publicProjectSuggestionses = new HashSet(0);
     private Set mtefBoVersions = new HashSet(0);
     private Set budgetPerformanceReviews = new HashSet(0);
     private Set budgetVersionStatuses = new HashSet(0);
     private Set requestDetailses = new HashSet(0);
     private Set keyFigureses = new HashSet(0);
     private Set budgetTimetables = new HashSet(0);
     private Set budgetVersionses = new HashSet(0);
     private Set mtssMdaCeilings = new HashSet(0);

    public BudgetYears() {
    }

	
    public BudgetYears(int id, String name, int year, boolean isCurrentBaseYear, Date dateCreated, int orgId) {
        this.id = id;
        this.name = name;
        this.year = year;
        this.isCurrentBaseYear = isCurrentBaseYear;
        this.dateCreated = dateCreated;
        this.orgId = orgId;
    }
    public BudgetYears(int id, String name, int year, boolean isCurrentBaseYear, Date dateCreated, int orgId, Set mtefDepartmentFigureses, Set mybfFigureses, Set mtssSubSectorCeilings, Set mtssSectorCeilings, Set publicProjectSuggestionses, Set mtefBoVersions, Set budgetPerformanceReviews, Set budgetVersionStatuses, Set requestDetailses, Set keyFigureses, Set budgetTimetables, Set budgetVersionses, Set mtssMdaCeilings) {
       this.id = id;
       this.name = name;
       this.year = year;
       this.isCurrentBaseYear = isCurrentBaseYear;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.mtefDepartmentFigureses = mtefDepartmentFigureses;
       this.mybfFigureses = mybfFigureses;
       this.mtssSubSectorCeilings = mtssSubSectorCeilings;
       this.mtssSectorCeilings = mtssSectorCeilings;
       this.publicProjectSuggestionses = publicProjectSuggestionses;
       this.mtefBoVersions = mtefBoVersions;
       this.budgetPerformanceReviews = budgetPerformanceReviews;
       this.budgetVersionStatuses = budgetVersionStatuses;
       this.requestDetailses = requestDetailses;
       this.keyFigureses = keyFigureses;
       this.budgetTimetables = budgetTimetables;
       this.budgetVersionses = budgetVersionses;
       this.mtssMdaCeilings = mtssMdaCeilings;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public boolean isIsCurrentBaseYear() {
        return this.isCurrentBaseYear;
    }
    
    public void setIsCurrentBaseYear(boolean isCurrentBaseYear) {
        this.isCurrentBaseYear = isCurrentBaseYear;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public Set getMtefDepartmentFigureses() {
        return this.mtefDepartmentFigureses;
    }
    
    public void setMtefDepartmentFigureses(Set mtefDepartmentFigureses) {
        this.mtefDepartmentFigureses = mtefDepartmentFigureses;
    }
    public Set getMybfFigureses() {
        return this.mybfFigureses;
    }
    
    public void setMybfFigureses(Set mybfFigureses) {
        this.mybfFigureses = mybfFigureses;
    }
    public Set getMtssSubSectorCeilings() {
        return this.mtssSubSectorCeilings;
    }
    
    public void setMtssSubSectorCeilings(Set mtssSubSectorCeilings) {
        this.mtssSubSectorCeilings = mtssSubSectorCeilings;
    }
    public Set getMtssSectorCeilings() {
        return this.mtssSectorCeilings;
    }
    
    public void setMtssSectorCeilings(Set mtssSectorCeilings) {
        this.mtssSectorCeilings = mtssSectorCeilings;
    }
    public Set getPublicProjectSuggestionses() {
        return this.publicProjectSuggestionses;
    }
    
    public void setPublicProjectSuggestionses(Set publicProjectSuggestionses) {
        this.publicProjectSuggestionses = publicProjectSuggestionses;
    }
    public Set getMtefBoVersions() {
        return this.mtefBoVersions;
    }
    
    public void setMtefBoVersions(Set mtefBoVersions) {
        this.mtefBoVersions = mtefBoVersions;
    }
    public Set getBudgetPerformanceReviews() {
        return this.budgetPerformanceReviews;
    }
    
    public void setBudgetPerformanceReviews(Set budgetPerformanceReviews) {
        this.budgetPerformanceReviews = budgetPerformanceReviews;
    }
    public Set getBudgetVersionStatuses() {
        return this.budgetVersionStatuses;
    }
    
    public void setBudgetVersionStatuses(Set budgetVersionStatuses) {
        this.budgetVersionStatuses = budgetVersionStatuses;
    }
    public Set getRequestDetailses() {
        return this.requestDetailses;
    }
    
    public void setRequestDetailses(Set requestDetailses) {
        this.requestDetailses = requestDetailses;
    }
    public Set getKeyFigureses() {
        return this.keyFigureses;
    }
    
    public void setKeyFigureses(Set keyFigureses) {
        this.keyFigureses = keyFigureses;
    }
    public Set getBudgetTimetables() {
        return this.budgetTimetables;
    }
    
    public void setBudgetTimetables(Set budgetTimetables) {
        this.budgetTimetables = budgetTimetables;
    }
    public Set getBudgetVersionses() {
        return this.budgetVersionses;
    }
    
    public void setBudgetVersionses(Set budgetVersionses) {
        this.budgetVersionses = budgetVersionses;
    }
    public Set getMtssMdaCeilings() {
        return this.mtssMdaCeilings;
    }
    
    public void setMtssMdaCeilings(Set mtssMdaCeilings) {
        this.mtssMdaCeilings = mtssMdaCeilings;
    }




}


