package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BudgetTypeComponents generated by hbm2java
 */
public class BudgetTypeComponents  implements java.io.Serializable {


     private int id;
     private BudgetTypeComponentTypes budgetTypeComponentTypes;
     private BudgetTypes budgetTypes;
     private String name;
     private boolean isBudgeted;
     private Date dateCreated;
     private String glAccount;
     private Integer orgId;
     private Set mtssSubSectorCeilings = new HashSet(0);
     private Set mtssSectorCeilings = new HashSet(0);
     private Set mtssMdaCeilings = new HashSet(0);
     private Set mybfFigureses = new HashSet(0);

    public BudgetTypeComponents() {
    }

	
    public BudgetTypeComponents(int id, BudgetTypeComponentTypes budgetTypeComponentTypes, BudgetTypes budgetTypes, String name, boolean isBudgeted, Date dateCreated) {
        this.id = id;
        this.budgetTypeComponentTypes = budgetTypeComponentTypes;
        this.budgetTypes = budgetTypes;
        this.name = name;
        this.isBudgeted = isBudgeted;
        this.dateCreated = dateCreated;
    }
    public BudgetTypeComponents(int id, BudgetTypeComponentTypes budgetTypeComponentTypes, BudgetTypes budgetTypes, String name, boolean isBudgeted, Date dateCreated, String glAccount, Integer orgId, Set mtssSubSectorCeilings, Set mtssSectorCeilings, Set mtssMdaCeilings, Set mybfFigureses) {
       this.id = id;
       this.budgetTypeComponentTypes = budgetTypeComponentTypes;
       this.budgetTypes = budgetTypes;
       this.name = name;
       this.isBudgeted = isBudgeted;
       this.dateCreated = dateCreated;
       this.glAccount = glAccount;
       this.orgId = orgId;
       this.mtssSubSectorCeilings = mtssSubSectorCeilings;
       this.mtssSectorCeilings = mtssSectorCeilings;
       this.mtssMdaCeilings = mtssMdaCeilings;
       this.mybfFigureses = mybfFigureses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTypeComponentTypes getBudgetTypeComponentTypes() {
        return this.budgetTypeComponentTypes;
    }
    
    public void setBudgetTypeComponentTypes(BudgetTypeComponentTypes budgetTypeComponentTypes) {
        this.budgetTypeComponentTypes = budgetTypeComponentTypes;
    }
    public BudgetTypes getBudgetTypes() {
        return this.budgetTypes;
    }
    
    public void setBudgetTypes(BudgetTypes budgetTypes) {
        this.budgetTypes = budgetTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsBudgeted() {
        return this.isBudgeted;
    }
    
    public void setIsBudgeted(boolean isBudgeted) {
        this.isBudgeted = isBudgeted;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getGlAccount() {
        return this.glAccount;
    }
    
    public void setGlAccount(String glAccount) {
        this.glAccount = glAccount;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getMtssSubSectorCeilings() {
        return this.mtssSubSectorCeilings;
    }
    
    public void setMtssSubSectorCeilings(Set mtssSubSectorCeilings) {
        this.mtssSubSectorCeilings = mtssSubSectorCeilings;
    }
    public Set getMtssSectorCeilings() {
        return this.mtssSectorCeilings;
    }
    
    public void setMtssSectorCeilings(Set mtssSectorCeilings) {
        this.mtssSectorCeilings = mtssSectorCeilings;
    }
    public Set getMtssMdaCeilings() {
        return this.mtssMdaCeilings;
    }
    
    public void setMtssMdaCeilings(Set mtssMdaCeilings) {
        this.mtssMdaCeilings = mtssMdaCeilings;
    }
    public Set getMybfFigureses() {
        return this.mybfFigureses;
    }
    
    public void setMybfFigureses(Set mybfFigureses) {
        this.mybfFigureses = mybfFigureses;
    }




}


