package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Currencies generated by hbm2java
 */
public class Currencies  implements java.io.Serializable {


     private int id;
     private String countryName;
     private String currencyName;
     private String currencySymbol;
     private Double currencyRate;
     private Date dateCreated;
     private Integer orgId;

    public Currencies() {
    }

	
    public Currencies(int id) {
        this.id = id;
    }
    public Currencies(int id, String countryName, String currencyName, String currencySymbol, Double currencyRate, Date dateCreated, Integer orgId) {
       this.id = id;
       this.countryName = countryName;
       this.currencyName = currencyName;
       this.currencySymbol = currencySymbol;
       this.currencyRate = currencyRate;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public String getCurrencyName() {
        return this.currencyName;
    }
    
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }
    public String getCurrencySymbol() {
        return this.currencySymbol;
    }
    
    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }
    public Double getCurrencyRate() {
        return this.currencyRate;
    }
    
    public void setCurrencyRate(Double currencyRate) {
        this.currencyRate = currencyRate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


