package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DepartmentHod generated by hbm2java
 */
public class DepartmentHod  implements java.io.Serializable {


     private int id;
     private Departments departments;
     private Users users;
     private Date dateCreated;
     private Integer orgId;

    public DepartmentHod() {
    }

	
    public DepartmentHod(int id, Departments departments, Users users) {
        this.id = id;
        this.departments = departments;
        this.users = users;
    }
    public DepartmentHod(int id, Departments departments, Users users, Date dateCreated, Integer orgId) {
       this.id = id;
       this.departments = departments;
       this.users = users;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


