package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EconomicSegmentHeader2 generated by hbm2java
 */
public class EconomicSegmentHeader2  implements java.io.Serializable {


     private int id;
     private EconomicSegmentHeader1 economicSegmentHeader1;
     private String name;
     private String code;
     private Date dateCreated;
     private Integer orgId;
     private Set economicSegmentHeader3s = new HashSet(0);

    public EconomicSegmentHeader2() {
    }

	
    public EconomicSegmentHeader2(int id, EconomicSegmentHeader1 economicSegmentHeader1, String name, String code, Date dateCreated) {
        this.id = id;
        this.economicSegmentHeader1 = economicSegmentHeader1;
        this.name = name;
        this.code = code;
        this.dateCreated = dateCreated;
    }
    public EconomicSegmentHeader2(int id, EconomicSegmentHeader1 economicSegmentHeader1, String name, String code, Date dateCreated, Integer orgId, Set economicSegmentHeader3s) {
       this.id = id;
       this.economicSegmentHeader1 = economicSegmentHeader1;
       this.name = name;
       this.code = code;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.economicSegmentHeader3s = economicSegmentHeader3s;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EconomicSegmentHeader1 getEconomicSegmentHeader1() {
        return this.economicSegmentHeader1;
    }
    
    public void setEconomicSegmentHeader1(EconomicSegmentHeader1 economicSegmentHeader1) {
        this.economicSegmentHeader1 = economicSegmentHeader1;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getEconomicSegmentHeader3s() {
        return this.economicSegmentHeader3s;
    }
    
    public void setEconomicSegmentHeader3s(Set economicSegmentHeader3s) {
        this.economicSegmentHeader3s = economicSegmentHeader3s;
    }




}


