package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EconomicSegmentHeader4 generated by hbm2java
 */
public class EconomicSegmentHeader4  implements java.io.Serializable {


     private int id;
     private EconomicSegmentHeader3 economicSegmentHeader3;
     private String name;
     private String code;
     private Date dateCreated;
     private Integer orgId;
     private Set economicSegments = new HashSet(0);

    public EconomicSegmentHeader4() {
    }

	
    public EconomicSegmentHeader4(int id, EconomicSegmentHeader3 economicSegmentHeader3, String name, String code, Date dateCreated) {
        this.id = id;
        this.economicSegmentHeader3 = economicSegmentHeader3;
        this.name = name;
        this.code = code;
        this.dateCreated = dateCreated;
    }
    public EconomicSegmentHeader4(int id, EconomicSegmentHeader3 economicSegmentHeader3, String name, String code, Date dateCreated, Integer orgId, Set economicSegments) {
       this.id = id;
       this.economicSegmentHeader3 = economicSegmentHeader3;
       this.name = name;
       this.code = code;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.economicSegments = economicSegments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EconomicSegmentHeader3 getEconomicSegmentHeader3() {
        return this.economicSegmentHeader3;
    }
    
    public void setEconomicSegmentHeader3(EconomicSegmentHeader3 economicSegmentHeader3) {
        this.economicSegmentHeader3 = economicSegmentHeader3;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getEconomicSegments() {
        return this.economicSegments;
    }
    
    public void setEconomicSegments(Set economicSegments) {
        this.economicSegments = economicSegments;
    }




}


