package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FrameworkParameterTypes generated by hbm2java
 */
public class FrameworkParameterTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private boolean isRate;
     private Date dateCreated;
     private int orgId;
     private Set frameworkParameterses = new HashSet(0);

    public FrameworkParameterTypes() {
    }

	
    public FrameworkParameterTypes(int id, String name, boolean isRate, Date dateCreated, int orgId) {
        this.id = id;
        this.name = name;
        this.isRate = isRate;
        this.dateCreated = dateCreated;
        this.orgId = orgId;
    }
    public FrameworkParameterTypes(int id, String name, boolean isRate, Date dateCreated, int orgId, Set frameworkParameterses) {
       this.id = id;
       this.name = name;
       this.isRate = isRate;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.frameworkParameterses = frameworkParameterses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsRate() {
        return this.isRate;
    }
    
    public void setIsRate(boolean isRate) {
        this.isRate = isRate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public Set getFrameworkParameterses() {
        return this.frameworkParameterses;
    }
    
    public void setFrameworkParameterses(Set frameworkParameterses) {
        this.frameworkParameterses = frameworkParameterses;
    }




}


