package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FrameworkParameters generated by hbm2java
 */
public class FrameworkParameters  implements java.io.Serializable {


     private int id;
     private FrameworkParameterTypes frameworkParameterTypes;
     private double value;
     private int year;
     private Date dateCreated;
     private Integer orgId;

    public FrameworkParameters() {
    }

	
    public FrameworkParameters(int id, FrameworkParameterTypes frameworkParameterTypes, double value, int year, Date dateCreated) {
        this.id = id;
        this.frameworkParameterTypes = frameworkParameterTypes;
        this.value = value;
        this.year = year;
        this.dateCreated = dateCreated;
    }
    public FrameworkParameters(int id, FrameworkParameterTypes frameworkParameterTypes, double value, int year, Date dateCreated, Integer orgId) {
       this.id = id;
       this.frameworkParameterTypes = frameworkParameterTypes;
       this.value = value;
       this.year = year;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FrameworkParameterTypes getFrameworkParameterTypes() {
        return this.frameworkParameterTypes;
    }
    
    public void setFrameworkParameterTypes(FrameworkParameterTypes frameworkParameterTypes) {
        this.frameworkParameterTypes = frameworkParameterTypes;
    }
    public double getValue() {
        return this.value;
    }
    
    public void setValue(double value) {
        this.value = value;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


