package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FunctionalSegment generated by hbm2java
 */
public class FunctionalSegment  implements java.io.Serializable {


     private int id;
     private FunctionalSegmentHeader2 functionalSegmentHeader2;
     private String name;
     private String code;
     private Date dateCreated;
     private Integer orgId;

    public FunctionalSegment() {
    }

	
    public FunctionalSegment(int id, FunctionalSegmentHeader2 functionalSegmentHeader2, String name, Date dateCreated) {
        this.id = id;
        this.functionalSegmentHeader2 = functionalSegmentHeader2;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public FunctionalSegment(int id, FunctionalSegmentHeader2 functionalSegmentHeader2, String name, String code, Date dateCreated, Integer orgId) {
       this.id = id;
       this.functionalSegmentHeader2 = functionalSegmentHeader2;
       this.name = name;
       this.code = code;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FunctionalSegmentHeader2 getFunctionalSegmentHeader2() {
        return this.functionalSegmentHeader2;
    }
    
    public void setFunctionalSegmentHeader2(FunctionalSegmentHeader2 functionalSegmentHeader2) {
        this.functionalSegmentHeader2 = functionalSegmentHeader2;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


