package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FunctionalSegmentHeader1 generated by hbm2java
 */
public class FunctionalSegmentHeader1  implements java.io.Serializable {


     private int id;
     private Integer orgId;
     private Date dateCreated;
     private String name;
     private String code;
     private Set functionalSegmentHeader2s = new HashSet(0);

    public FunctionalSegmentHeader1() {
    }

	
    public FunctionalSegmentHeader1(int id, Date dateCreated, String name) {
        this.id = id;
        this.dateCreated = dateCreated;
        this.name = name;
    }
    public FunctionalSegmentHeader1(int id, Integer orgId, Date dateCreated, String name, String code, Set functionalSegmentHeader2s) {
       this.id = id;
       this.orgId = orgId;
       this.dateCreated = dateCreated;
       this.name = name;
       this.code = code;
       this.functionalSegmentHeader2s = functionalSegmentHeader2s;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getFunctionalSegmentHeader2s() {
        return this.functionalSegmentHeader2s;
    }
    
    public void setFunctionalSegmentHeader2s(Set functionalSegmentHeader2s) {
        this.functionalSegmentHeader2s = functionalSegmentHeader2s;
    }




}


