package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GeographicSegmentHeader2 generated by hbm2java
 */
public class GeographicSegmentHeader2  implements java.io.Serializable {


     private int id;
     private GeographicSegmentHeader1 geographicSegmentHeader1;
     private String name;
     private String code;
     private Date dateCreated;
     private Integer orgId;
     private Set geographicSegmentHeader3s = new HashSet(0);

    public GeographicSegmentHeader2() {
    }

	
    public GeographicSegmentHeader2(int id, GeographicSegmentHeader1 geographicSegmentHeader1, String name, String code, Date dateCreated) {
        this.id = id;
        this.geographicSegmentHeader1 = geographicSegmentHeader1;
        this.name = name;
        this.code = code;
        this.dateCreated = dateCreated;
    }
    public GeographicSegmentHeader2(int id, GeographicSegmentHeader1 geographicSegmentHeader1, String name, String code, Date dateCreated, Integer orgId, Set geographicSegmentHeader3s) {
       this.id = id;
       this.geographicSegmentHeader1 = geographicSegmentHeader1;
       this.name = name;
       this.code = code;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.geographicSegmentHeader3s = geographicSegmentHeader3s;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public GeographicSegmentHeader1 getGeographicSegmentHeader1() {
        return this.geographicSegmentHeader1;
    }
    
    public void setGeographicSegmentHeader1(GeographicSegmentHeader1 geographicSegmentHeader1) {
        this.geographicSegmentHeader1 = geographicSegmentHeader1;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getGeographicSegmentHeader3s() {
        return this.geographicSegmentHeader3s;
    }
    
    public void setGeographicSegmentHeader3s(Set geographicSegmentHeader3s) {
        this.geographicSegmentHeader3s = geographicSegmentHeader3s;
    }




}


