package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Goals generated by hbm2java
 */
public class Goals  implements java.io.Serializable {


     private int id;
     private String description;
     private Date goalDate;
     private int policyId;
     private Date dateCreated;
     private Integer orgId;
     private Set outcomeses = new HashSet(0);

    public Goals() {
    }

	
    public Goals(int id, Date goalDate, int policyId, Date dateCreated) {
        this.id = id;
        this.goalDate = goalDate;
        this.policyId = policyId;
        this.dateCreated = dateCreated;
    }
    public Goals(int id, String description, Date goalDate, int policyId, Date dateCreated, Integer orgId, Set outcomeses) {
       this.id = id;
       this.description = description;
       this.goalDate = goalDate;
       this.policyId = policyId;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.outcomeses = outcomeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getGoalDate() {
        return this.goalDate;
    }
    
    public void setGoalDate(Date goalDate) {
        this.goalDate = goalDate;
    }
    public int getPolicyId() {
        return this.policyId;
    }
    
    public void setPolicyId(int policyId) {
        this.policyId = policyId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getOutcomeses() {
        return this.outcomeses;
    }
    
    public void setOutcomeses(Set outcomeses) {
        this.outcomeses = outcomeses;
    }




}


