package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Incomes generated by hbm2java
 */
public class Incomes  implements java.io.Serializable {


     private int id;
     private Outputs outputs;
     private String description;
     private Date incomeDate;
     private Date dateCreated;
     private Integer orgId;

    public Incomes() {
    }

	
    public Incomes(int id, Outputs outputs, Date incomeDate, Date dateCreated) {
        this.id = id;
        this.outputs = outputs;
        this.incomeDate = incomeDate;
        this.dateCreated = dateCreated;
    }
    public Incomes(int id, Outputs outputs, String description, Date incomeDate, Date dateCreated, Integer orgId) {
       this.id = id;
       this.outputs = outputs;
       this.description = description;
       this.incomeDate = incomeDate;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Outputs getOutputs() {
        return this.outputs;
    }
    
    public void setOutputs(Outputs outputs) {
        this.outputs = outputs;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getIncomeDate() {
        return this.incomeDate;
    }
    
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


