package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lgas generated by hbm2java
 */
public class Lgas  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private Set publicProjectSuggestionses = new HashSet(0);

    public Lgas() {
    }

	
    public Lgas(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public Lgas(int id, String name, Date dateCreated, Integer orgId, Set publicProjectSuggestionses) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.publicProjectSuggestionses = publicProjectSuggestionses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getPublicProjectSuggestionses() {
        return this.publicProjectSuggestionses;
    }
    
    public void setPublicProjectSuggestionses(Set publicProjectSuggestionses) {
        this.publicProjectSuggestionses = publicProjectSuggestionses;
    }




}


