package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mdas generated by hbm2java
 */
public class Mdas  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private String mdaType;
     private Double mdaWeight;
     private String administrativeSegment;
     private String subSectorCode;
     private Set requestAgentses = new HashSet(0);

    public Mdas() {
    }

	
    public Mdas(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public Mdas(int id, String name, Date dateCreated, Integer orgId, String mdaType, Double mdaWeight, String administrativeSegment, String subSectorCode, Set requestAgentses) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.mdaType = mdaType;
       this.mdaWeight = mdaWeight;
       this.administrativeSegment = administrativeSegment;
       this.subSectorCode = subSectorCode;
       this.requestAgentses = requestAgentses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public String getMdaType() {
        return this.mdaType;
    }
    
    public void setMdaType(String mdaType) {
        this.mdaType = mdaType;
    }
    public Double getMdaWeight() {
        return this.mdaWeight;
    }
    
    public void setMdaWeight(Double mdaWeight) {
        this.mdaWeight = mdaWeight;
    }
    public String getAdministrativeSegment() {
        return this.administrativeSegment;
    }
    
    public void setAdministrativeSegment(String administrativeSegment) {
        this.administrativeSegment = administrativeSegment;
    }
    public String getSubSectorCode() {
        return this.subSectorCode;
    }
    
    public void setSubSectorCode(String subSectorCode) {
        this.subSectorCode = subSectorCode;
    }
    public Set getRequestAgentses() {
        return this.requestAgentses;
    }
    
    public void setRequestAgentses(Set requestAgentses) {
        this.requestAgentses = requestAgentses;
    }




}


