package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MeetingDetails generated by hbm2java
 */
public class MeetingDetails  implements java.io.Serializable {


     private int id;
     private BudgetTimetableActivities budgetTimetableActivities;
     private String name;
     private String venue;
     private Date meetingDate;
     private Date dateCreated;
     private Integer orgId;
     private Set meetingDeliberationses = new HashSet(0);
     private Set meetingAttendantses = new HashSet(0);
     private Set meetingAgendaDetailses = new HashSet(0);

    public MeetingDetails() {
    }

	
    public MeetingDetails(int id, BudgetTimetableActivities budgetTimetableActivities, String name, String venue, Date meetingDate, Date dateCreated) {
        this.id = id;
        this.budgetTimetableActivities = budgetTimetableActivities;
        this.name = name;
        this.venue = venue;
        this.meetingDate = meetingDate;
        this.dateCreated = dateCreated;
    }
    public MeetingDetails(int id, BudgetTimetableActivities budgetTimetableActivities, String name, String venue, Date meetingDate, Date dateCreated, Integer orgId, Set meetingDeliberationses, Set meetingAttendantses, Set meetingAgendaDetailses) {
       this.id = id;
       this.budgetTimetableActivities = budgetTimetableActivities;
       this.name = name;
       this.venue = venue;
       this.meetingDate = meetingDate;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.meetingDeliberationses = meetingDeliberationses;
       this.meetingAttendantses = meetingAttendantses;
       this.meetingAgendaDetailses = meetingAgendaDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTimetableActivities getBudgetTimetableActivities() {
        return this.budgetTimetableActivities;
    }
    
    public void setBudgetTimetableActivities(BudgetTimetableActivities budgetTimetableActivities) {
        this.budgetTimetableActivities = budgetTimetableActivities;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }
    public Date getMeetingDate() {
        return this.meetingDate;
    }
    
    public void setMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getMeetingDeliberationses() {
        return this.meetingDeliberationses;
    }
    
    public void setMeetingDeliberationses(Set meetingDeliberationses) {
        this.meetingDeliberationses = meetingDeliberationses;
    }
    public Set getMeetingAttendantses() {
        return this.meetingAttendantses;
    }
    
    public void setMeetingAttendantses(Set meetingAttendantses) {
        this.meetingAttendantses = meetingAttendantses;
    }
    public Set getMeetingAgendaDetailses() {
        return this.meetingAgendaDetailses;
    }
    
    public void setMeetingAgendaDetailses(Set meetingAgendaDetailses) {
        this.meetingAgendaDetailses = meetingAgendaDetailses;
    }




}


