package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MeetingAttendants generated by hbm2java
 */
public class MeetingAttendants  implements java.io.Serializable {


     private int id;
     private MeetingDetails meetingDetails;
     private MeetingRoles meetingRoles;
     private Users users;
     private Date dateCreated;
     private Integer orgId;

    public MeetingAttendants() {
    }

	
    public MeetingAttendants(int id, MeetingDetails meetingDetails, MeetingRoles meetingRoles, Users users, Date dateCreated) {
        this.id = id;
        this.meetingDetails = meetingDetails;
        this.meetingRoles = meetingRoles;
        this.users = users;
        this.dateCreated = dateCreated;
    }
    public MeetingAttendants(int id, MeetingDetails meetingDetails, MeetingRoles meetingRoles, Users users, Date dateCreated, Integer orgId) {
       this.id = id;
       this.meetingDetails = meetingDetails;
       this.meetingRoles = meetingRoles;
       this.users = users;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MeetingDetails getMeetingDetails() {
        return this.meetingDetails;
    }
    
    public void setMeetingDetails(MeetingDetails meetingDetails) {
        this.meetingDetails = meetingDetails;
    }
    public MeetingRoles getMeetingRoles() {
        return this.meetingRoles;
    }
    
    public void setMeetingRoles(MeetingRoles meetingRoles) {
        this.meetingRoles = meetingRoles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


