package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MeetingAgendaDetails generated by hbm2java
 */
public class MeetingAgendaDetails  implements java.io.Serializable {


     private int id;
     private MeetingAgenda meetingAgenda;
     private MeetingDetails meetingDetails;
     private String name;
     private Date dateCreated;
     private Integer orgId;

    public MeetingAgendaDetails() {
    }

	
    public MeetingAgendaDetails(int id, MeetingAgenda meetingAgenda, MeetingDetails meetingDetails, String name, Date dateCreated) {
        this.id = id;
        this.meetingAgenda = meetingAgenda;
        this.meetingDetails = meetingDetails;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public MeetingAgendaDetails(int id, MeetingAgenda meetingAgenda, MeetingDetails meetingDetails, String name, Date dateCreated, Integer orgId) {
       this.id = id;
       this.meetingAgenda = meetingAgenda;
       this.meetingDetails = meetingDetails;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MeetingAgenda getMeetingAgenda() {
        return this.meetingAgenda;
    }
    
    public void setMeetingAgenda(MeetingAgenda meetingAgenda) {
        this.meetingAgenda = meetingAgenda;
    }
    public MeetingDetails getMeetingDetails() {
        return this.meetingDetails;
    }
    
    public void setMeetingDetails(MeetingDetails meetingDetails) {
        this.meetingDetails = meetingDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


