package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MenuCategory generated by hbm2java
 */
public class MenuCategory  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private Integer rank;
     private Set systemMenus = new HashSet(0);

    public MenuCategory() {
    }

	
    public MenuCategory(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public MenuCategory(int id, String name, Date dateCreated, Integer orgId, Integer rank, Set systemMenus) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.rank = rank;
       this.systemMenus = systemMenus;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
    public Set getSystemMenus() {
        return this.systemMenus;
    }
    
    public void setSystemMenus(Set systemMenus) {
        this.systemMenus = systemMenus;
    }




}


