package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MenuRole generated by hbm2java
 */
public class MenuRole  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private SystemMenu systemMenu;
     private Date dateCreated;
     private Integer orgId;

    public MenuRole() {
    }

	
    public MenuRole(int id, Roles roles, SystemMenu systemMenu, Date dateCreated) {
        this.id = id;
        this.roles = roles;
        this.systemMenu = systemMenu;
        this.dateCreated = dateCreated;
    }
    public MenuRole(int id, Roles roles, SystemMenu systemMenu, Date dateCreated, Integer orgId) {
       this.id = id;
       this.roles = roles;
       this.systemMenu = systemMenu;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public SystemMenu getSystemMenu() {
        return this.systemMenu;
    }
    
    public void setSystemMenu(SystemMenu systemMenu) {
        this.systemMenu = systemMenu;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


