package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MenuUser generated by hbm2java
 */
public class MenuUser  implements java.io.Serializable {


     private int id;
     private SystemMenu systemMenu;
     private Users users;
     private String accessible;
     private Date dateCreated;
     private Integer orgId;

    public MenuUser() {
    }

	
    public MenuUser(int id, SystemMenu systemMenu, Users users, String accessible, Date dateCreated) {
        this.id = id;
        this.systemMenu = systemMenu;
        this.users = users;
        this.accessible = accessible;
        this.dateCreated = dateCreated;
    }
    public MenuUser(int id, SystemMenu systemMenu, Users users, String accessible, Date dateCreated, Integer orgId) {
       this.id = id;
       this.systemMenu = systemMenu;
       this.users = users;
       this.accessible = accessible;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SystemMenu getSystemMenu() {
        return this.systemMenu;
    }
    
    public void setSystemMenu(SystemMenu systemMenu) {
        this.systemMenu = systemMenu;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getAccessible() {
        return this.accessible;
    }
    
    public void setAccessible(String accessible) {
        this.accessible = accessible;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


