package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private int id;
     private MessageTypes messageTypes;
     private String title;
     private String message;
     private String recipients;
     private Date dateCreated;
     private Integer orgId;

    public Messages() {
    }

	
    public Messages(int id, MessageTypes messageTypes, Date dateCreated) {
        this.id = id;
        this.messageTypes = messageTypes;
        this.dateCreated = dateCreated;
    }
    public Messages(int id, MessageTypes messageTypes, String title, String message, String recipients, Date dateCreated, Integer orgId) {
       this.id = id;
       this.messageTypes = messageTypes;
       this.title = title;
       this.message = message;
       this.recipients = recipients;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MessageTypes getMessageTypes() {
        return this.messageTypes;
    }
    
    public void setMessageTypes(MessageTypes messageTypes) {
        this.messageTypes = messageTypes;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getRecipients() {
        return this.recipients;
    }
    
    public void setRecipients(String recipients) {
        this.recipients = recipients;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


