package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MtssMdaCeiling generated by hbm2java
 */
public class MtssMdaCeiling  implements java.io.Serializable {


     private int id;
     private BudgetTypeComponents budgetTypeComponents;
     private BudgetYears budgetYears;
     private int mdaId;
     private Double totalAmount;
     private Date dateCreated;
     private int orgId;
     private Double mdaWeight;
     private Integer subSectorId;

    public MtssMdaCeiling() {
    }

	
    public MtssMdaCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int mdaId, Date dateCreated, int orgId) {
        this.id = id;
        this.budgetTypeComponents = budgetTypeComponents;
        this.budgetYears = budgetYears;
        this.mdaId = mdaId;
        this.dateCreated = dateCreated;
        this.orgId = orgId;
    }
    public MtssMdaCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int mdaId, Double totalAmount, Date dateCreated, int orgId, Double mdaWeight, Integer subSectorId) {
       this.id = id;
       this.budgetTypeComponents = budgetTypeComponents;
       this.budgetYears = budgetYears;
       this.mdaId = mdaId;
       this.totalAmount = totalAmount;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.mdaWeight = mdaWeight;
       this.subSectorId = subSectorId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTypeComponents getBudgetTypeComponents() {
        return this.budgetTypeComponents;
    }
    
    public void setBudgetTypeComponents(BudgetTypeComponents budgetTypeComponents) {
        this.budgetTypeComponents = budgetTypeComponents;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public int getMdaId() {
        return this.mdaId;
    }
    
    public void setMdaId(int mdaId) {
        this.mdaId = mdaId;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public Double getMdaWeight() {
        return this.mdaWeight;
    }
    
    public void setMdaWeight(Double mdaWeight) {
        this.mdaWeight = mdaWeight;
    }
    public Integer getSubSectorId() {
        return this.subSectorId;
    }
    
    public void setSubSectorId(Integer subSectorId) {
        this.subSectorId = subSectorId;
    }




}


