package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MtssSubSectorCeiling generated by hbm2java
 */
public class MtssSubSectorCeiling  implements java.io.Serializable {


     private int id;
     private BudgetTypeComponents budgetTypeComponents;
     private BudgetYears budgetYears;
     private int subSectorId;
     private Double totalAmount;
     private Date dateCreated;
     private int orgId;
     private Double subSectorWeight;

    public MtssSubSectorCeiling() {
    }

	
    public MtssSubSectorCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int subSectorId, Date dateCreated, int orgId) {
        this.id = id;
        this.budgetTypeComponents = budgetTypeComponents;
        this.budgetYears = budgetYears;
        this.subSectorId = subSectorId;
        this.dateCreated = dateCreated;
        this.orgId = orgId;
    }
    public MtssSubSectorCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int subSectorId, Double totalAmount, Date dateCreated, int orgId, Double subSectorWeight) {
       this.id = id;
       this.budgetTypeComponents = budgetTypeComponents;
       this.budgetYears = budgetYears;
       this.subSectorId = subSectorId;
       this.totalAmount = totalAmount;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.subSectorWeight = subSectorWeight;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTypeComponents getBudgetTypeComponents() {
        return this.budgetTypeComponents;
    }
    
    public void setBudgetTypeComponents(BudgetTypeComponents budgetTypeComponents) {
        this.budgetTypeComponents = budgetTypeComponents;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public int getSubSectorId() {
        return this.subSectorId;
    }
    
    public void setSubSectorId(int subSectorId) {
        this.subSectorId = subSectorId;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public Double getSubSectorWeight() {
        return this.subSectorWeight;
    }
    
    public void setSubSectorWeight(Double subSectorWeight) {
        this.subSectorWeight = subSectorWeight;
    }




}


