package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MtssSectorCeiling generated by hbm2java
 */
public class MtssSectorCeiling  implements java.io.Serializable {


     private int id;
     private BudgetTypeComponents budgetTypeComponents;
     private BudgetYears budgetYears;
     private int sectorId;
     private Double totalAmount;
     private Date dateCreated;
     private int orgId;
     private Double sectorWeight;

    public MtssSectorCeiling() {
    }

	
    public MtssSectorCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int sectorId, Date dateCreated, int orgId) {
        this.id = id;
        this.budgetTypeComponents = budgetTypeComponents;
        this.budgetYears = budgetYears;
        this.sectorId = sectorId;
        this.dateCreated = dateCreated;
        this.orgId = orgId;
    }
    public MtssSectorCeiling(int id, BudgetTypeComponents budgetTypeComponents, BudgetYears budgetYears, int sectorId, Double totalAmount, Date dateCreated, int orgId, Double sectorWeight) {
       this.id = id;
       this.budgetTypeComponents = budgetTypeComponents;
       this.budgetYears = budgetYears;
       this.sectorId = sectorId;
       this.totalAmount = totalAmount;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.sectorWeight = sectorWeight;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTypeComponents getBudgetTypeComponents() {
        return this.budgetTypeComponents;
    }
    
    public void setBudgetTypeComponents(BudgetTypeComponents budgetTypeComponents) {
        this.budgetTypeComponents = budgetTypeComponents;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public int getSectorId() {
        return this.sectorId;
    }
    
    public void setSectorId(int sectorId) {
        this.sectorId = sectorId;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public Double getSectorWeight() {
        return this.sectorWeight;
    }
    
    public void setSectorWeight(Double sectorWeight) {
        this.sectorWeight = sectorWeight;
    }




}


