package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MybfFigureOwnPercentageValues generated by hbm2java
 */
public class MybfFigureOwnPercentageValues  implements java.io.Serializable {


     private int id;
     private int mybfFigureId;
     private int percentage;
     private int year;
     private Date dateCreated;
     private Integer orgId;

    public MybfFigureOwnPercentageValues() {
    }

	
    public MybfFigureOwnPercentageValues(int id, int mybfFigureId, int percentage, int year, Date dateCreated) {
        this.id = id;
        this.mybfFigureId = mybfFigureId;
        this.percentage = percentage;
        this.year = year;
        this.dateCreated = dateCreated;
    }
    public MybfFigureOwnPercentageValues(int id, int mybfFigureId, int percentage, int year, Date dateCreated, Integer orgId) {
       this.id = id;
       this.mybfFigureId = mybfFigureId;
       this.percentage = percentage;
       this.year = year;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMybfFigureId() {
        return this.mybfFigureId;
    }
    
    public void setMybfFigureId(int mybfFigureId) {
        this.mybfFigureId = mybfFigureId;
    }
    public int getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(int percentage) {
        this.percentage = percentage;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


