package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MybfNarrations generated by hbm2java
 */
public class MybfNarrations  implements java.io.Serializable {


     private int id;
     private MybfFigures mybfFigures;
     private Users users;
     private String narration;
     private Date dateCreated;
     private Integer orgId;

    public MybfNarrations() {
    }

	
    public MybfNarrations(int id, MybfFigures mybfFigures, Users users, String narration, Date dateCreated) {
        this.id = id;
        this.mybfFigures = mybfFigures;
        this.users = users;
        this.narration = narration;
        this.dateCreated = dateCreated;
    }
    public MybfNarrations(int id, MybfFigures mybfFigures, Users users, String narration, Date dateCreated, Integer orgId) {
       this.id = id;
       this.mybfFigures = mybfFigures;
       this.users = users;
       this.narration = narration;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MybfFigures getMybfFigures() {
        return this.mybfFigures;
    }
    
    public void setMybfFigures(MybfFigures mybfFigures) {
        this.mybfFigures = mybfFigures;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNarration() {
        return this.narration;
    }
    
    public void setNarration(String narration) {
        this.narration = narration;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


