package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MybfFigures generated by hbm2java
 */
public class MybfFigures  implements java.io.Serializable {


     private int id;
     private BudgetTypeComponents budgetTypeComponents;
     private BudgetVersions budgetVersions;
     private BudgetYears budgetYears;
     private FrameworkMethods frameworkMethods;
     private Users users;
     private int mtefBoVersionId;
     private String chartOfAccount;
     private String budgetLine;
     private double budgetValue;
     private Date dateCreated;
     private Integer orgId;
     private Set mybfNarrationses = new HashSet(0);
     private Set mybfKpis = new HashSet(0);

    public MybfFigures() {
    }

	
    public MybfFigures(int id, BudgetTypeComponents budgetTypeComponents, BudgetVersions budgetVersions, BudgetYears budgetYears, FrameworkMethods frameworkMethods, Users users, int mtefBoVersionId, String chartOfAccount, String budgetLine, double budgetValue, Date dateCreated) {
        this.id = id;
        this.budgetTypeComponents = budgetTypeComponents;
        this.budgetVersions = budgetVersions;
        this.budgetYears = budgetYears;
        this.frameworkMethods = frameworkMethods;
        this.users = users;
        this.mtefBoVersionId = mtefBoVersionId;
        this.chartOfAccount = chartOfAccount;
        this.budgetLine = budgetLine;
        this.budgetValue = budgetValue;
        this.dateCreated = dateCreated;
    }
    public MybfFigures(int id, BudgetTypeComponents budgetTypeComponents, BudgetVersions budgetVersions, BudgetYears budgetYears, FrameworkMethods frameworkMethods, Users users, int mtefBoVersionId, String chartOfAccount, String budgetLine, double budgetValue, Date dateCreated, Integer orgId, Set mybfNarrationses, Set mybfKpis) {
       this.id = id;
       this.budgetTypeComponents = budgetTypeComponents;
       this.budgetVersions = budgetVersions;
       this.budgetYears = budgetYears;
       this.frameworkMethods = frameworkMethods;
       this.users = users;
       this.mtefBoVersionId = mtefBoVersionId;
       this.chartOfAccount = chartOfAccount;
       this.budgetLine = budgetLine;
       this.budgetValue = budgetValue;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.mybfNarrationses = mybfNarrationses;
       this.mybfKpis = mybfKpis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetTypeComponents getBudgetTypeComponents() {
        return this.budgetTypeComponents;
    }
    
    public void setBudgetTypeComponents(BudgetTypeComponents budgetTypeComponents) {
        this.budgetTypeComponents = budgetTypeComponents;
    }
    public BudgetVersions getBudgetVersions() {
        return this.budgetVersions;
    }
    
    public void setBudgetVersions(BudgetVersions budgetVersions) {
        this.budgetVersions = budgetVersions;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public FrameworkMethods getFrameworkMethods() {
        return this.frameworkMethods;
    }
    
    public void setFrameworkMethods(FrameworkMethods frameworkMethods) {
        this.frameworkMethods = frameworkMethods;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getMtefBoVersionId() {
        return this.mtefBoVersionId;
    }
    
    public void setMtefBoVersionId(int mtefBoVersionId) {
        this.mtefBoVersionId = mtefBoVersionId;
    }
    public String getChartOfAccount() {
        return this.chartOfAccount;
    }
    
    public void setChartOfAccount(String chartOfAccount) {
        this.chartOfAccount = chartOfAccount;
    }
    public String getBudgetLine() {
        return this.budgetLine;
    }
    
    public void setBudgetLine(String budgetLine) {
        this.budgetLine = budgetLine;
    }
    public double getBudgetValue() {
        return this.budgetValue;
    }
    
    public void setBudgetValue(double budgetValue) {
        this.budgetValue = budgetValue;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getMybfNarrationses() {
        return this.mybfNarrationses;
    }
    
    public void setMybfNarrationses(Set mybfNarrationses) {
        this.mybfNarrationses = mybfNarrationses;
    }
    public Set getMybfKpis() {
        return this.mybfKpis;
    }
    
    public void setMybfKpis(Set mybfKpis) {
        this.mybfKpis = mybfKpis;
    }




}


