package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MybfPreviousForward generated by hbm2java
 */
public class MybfPreviousForward  implements java.io.Serializable {


     private int id;
     private int mybfFigureId;
     private int budgetYear;
     private double budgetValue;
     private Date dateCreated;
     private Integer orgId;
     private Integer budgetTypeComponentId;

    public MybfPreviousForward() {
    }

	
    public MybfPreviousForward(int id, int mybfFigureId, int budgetYear, double budgetValue, Date dateCreated) {
        this.id = id;
        this.mybfFigureId = mybfFigureId;
        this.budgetYear = budgetYear;
        this.budgetValue = budgetValue;
        this.dateCreated = dateCreated;
    }
    public MybfPreviousForward(int id, int mybfFigureId, int budgetYear, double budgetValue, Date dateCreated, Integer orgId, Integer budgetTypeComponentId) {
       this.id = id;
       this.mybfFigureId = mybfFigureId;
       this.budgetYear = budgetYear;
       this.budgetValue = budgetValue;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.budgetTypeComponentId = budgetTypeComponentId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMybfFigureId() {
        return this.mybfFigureId;
    }
    
    public void setMybfFigureId(int mybfFigureId) {
        this.mybfFigureId = mybfFigureId;
    }
    public int getBudgetYear() {
        return this.budgetYear;
    }
    
    public void setBudgetYear(int budgetYear) {
        this.budgetYear = budgetYear;
    }
    public double getBudgetValue() {
        return this.budgetValue;
    }
    
    public void setBudgetValue(double budgetValue) {
        this.budgetValue = budgetValue;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Integer getBudgetTypeComponentId() {
        return this.budgetTypeComponentId;
    }
    
    public void setBudgetTypeComponentId(Integer budgetTypeComponentId) {
        this.budgetTypeComponentId = budgetTypeComponentId;
    }




}


