package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PerformanceGrades generated by hbm2java
 */
public class PerformanceGrades  implements java.io.Serializable {


     private int id;
     private String name;
     private Double score;
     private Date dateCreated;
     private Integer orgId;
     private Set budgetPerformanceReviews = new HashSet(0);

    public PerformanceGrades() {
    }

	
    public PerformanceGrades(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public PerformanceGrades(int id, String name, Double score, Date dateCreated, Integer orgId, Set budgetPerformanceReviews) {
       this.id = id;
       this.name = name;
       this.score = score;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.budgetPerformanceReviews = budgetPerformanceReviews;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getBudgetPerformanceReviews() {
        return this.budgetPerformanceReviews;
    }
    
    public void setBudgetPerformanceReviews(Set budgetPerformanceReviews) {
        this.budgetPerformanceReviews = budgetPerformanceReviews;
    }




}


