package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonnelCostItems generated by hbm2java
 */
public class PersonnelCostItems  implements java.io.Serializable {


     private int id;
     private String runId;
     private int year;
     private String objectType;
     private String objectId;
     private String costItem;
     private Date startDate;
     private Date endDate;
     private double amount;
     private double amountPerUnit;
     private String currencyKey;
     private String number;
     private String unit;
     private String period;
     private String interface_;
     private String hrPosition;
     private String costItemBas;
     private String orgGroup;
     private String indicatorDiffca;
     private String accAssignId;
     private String derived;
     private String eventId;
     private Date dateCreated;
     private Integer orgId;

    public PersonnelCostItems() {
    }

	
    public PersonnelCostItems(int id, String runId, int year, String objectType, String objectId, String costItem, Date startDate, Date endDate, double amount, double amountPerUnit, String currencyKey, String number, String period, String interface_, String hrPosition, String indicatorDiffca, String accAssignId, String eventId, Date dateCreated) {
        this.id = id;
        this.runId = runId;
        this.year = year;
        this.objectType = objectType;
        this.objectId = objectId;
        this.costItem = costItem;
        this.startDate = startDate;
        this.endDate = endDate;
        this.amount = amount;
        this.amountPerUnit = amountPerUnit;
        this.currencyKey = currencyKey;
        this.number = number;
        this.period = period;
        this.interface_ = interface_;
        this.hrPosition = hrPosition;
        this.indicatorDiffca = indicatorDiffca;
        this.accAssignId = accAssignId;
        this.eventId = eventId;
        this.dateCreated = dateCreated;
    }
    public PersonnelCostItems(int id, String runId, int year, String objectType, String objectId, String costItem, Date startDate, Date endDate, double amount, double amountPerUnit, String currencyKey, String number, String unit, String period, String interface_, String hrPosition, String costItemBas, String orgGroup, String indicatorDiffca, String accAssignId, String derived, String eventId, Date dateCreated, Integer orgId) {
       this.id = id;
       this.runId = runId;
       this.year = year;
       this.objectType = objectType;
       this.objectId = objectId;
       this.costItem = costItem;
       this.startDate = startDate;
       this.endDate = endDate;
       this.amount = amount;
       this.amountPerUnit = amountPerUnit;
       this.currencyKey = currencyKey;
       this.number = number;
       this.unit = unit;
       this.period = period;
       this.interface_ = interface_;
       this.hrPosition = hrPosition;
       this.costItemBas = costItemBas;
       this.orgGroup = orgGroup;
       this.indicatorDiffca = indicatorDiffca;
       this.accAssignId = accAssignId;
       this.derived = derived;
       this.eventId = eventId;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRunId() {
        return this.runId;
    }
    
    public void setRunId(String runId) {
        this.runId = runId;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public String getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }
    public String getCostItem() {
        return this.costItem;
    }
    
    public void setCostItem(String costItem) {
        this.costItem = costItem;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public double getAmountPerUnit() {
        return this.amountPerUnit;
    }
    
    public void setAmountPerUnit(double amountPerUnit) {
        this.amountPerUnit = amountPerUnit;
    }
    public String getCurrencyKey() {
        return this.currencyKey;
    }
    
    public void setCurrencyKey(String currencyKey) {
        this.currencyKey = currencyKey;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }
    public String getHrPosition() {
        return this.hrPosition;
    }
    
    public void setHrPosition(String hrPosition) {
        this.hrPosition = hrPosition;
    }
    public String getCostItemBas() {
        return this.costItemBas;
    }
    
    public void setCostItemBas(String costItemBas) {
        this.costItemBas = costItemBas;
    }
    public String getOrgGroup() {
        return this.orgGroup;
    }
    
    public void setOrgGroup(String orgGroup) {
        this.orgGroup = orgGroup;
    }
    public String getIndicatorDiffca() {
        return this.indicatorDiffca;
    }
    
    public void setIndicatorDiffca(String indicatorDiffca) {
        this.indicatorDiffca = indicatorDiffca;
    }
    public String getAccAssignId() {
        return this.accAssignId;
    }
    
    public void setAccAssignId(String accAssignId) {
        this.accAssignId = accAssignId;
    }
    public String getDerived() {
        return this.derived;
    }
    
    public void setDerived(String derived) {
        this.derived = derived;
    }
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


