package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonnelRelInfo generated by hbm2java
 */
public class PersonnelRelInfo  implements java.io.Serializable {


     private int id;
     private String runId;
     private int year;
     private String client;
     private String objectType;
     private String objectId;
     private Date startDate;
     private Date endDate;
     private int assignPercentage;
     private String hrPosition;
     private int hrNumberOfPositions;
     private Date dateCreated;
     private Integer orgId;

    public PersonnelRelInfo() {
    }

	
    public PersonnelRelInfo(int id, String runId, int year, String client, String objectType, String objectId, Date startDate, Date endDate, int assignPercentage, String hrPosition, int hrNumberOfPositions, Date dateCreated) {
        this.id = id;
        this.runId = runId;
        this.year = year;
        this.client = client;
        this.objectType = objectType;
        this.objectId = objectId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.assignPercentage = assignPercentage;
        this.hrPosition = hrPosition;
        this.hrNumberOfPositions = hrNumberOfPositions;
        this.dateCreated = dateCreated;
    }
    public PersonnelRelInfo(int id, String runId, int year, String client, String objectType, String objectId, Date startDate, Date endDate, int assignPercentage, String hrPosition, int hrNumberOfPositions, Date dateCreated, Integer orgId) {
       this.id = id;
       this.runId = runId;
       this.year = year;
       this.client = client;
       this.objectType = objectType;
       this.objectId = objectId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.assignPercentage = assignPercentage;
       this.hrPosition = hrPosition;
       this.hrNumberOfPositions = hrNumberOfPositions;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRunId() {
        return this.runId;
    }
    
    public void setRunId(String runId) {
        this.runId = runId;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public String getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getAssignPercentage() {
        return this.assignPercentage;
    }
    
    public void setAssignPercentage(int assignPercentage) {
        this.assignPercentage = assignPercentage;
    }
    public String getHrPosition() {
        return this.hrPosition;
    }
    
    public void setHrPosition(String hrPosition) {
        this.hrPosition = hrPosition;
    }
    public int getHrNumberOfPositions() {
        return this.hrNumberOfPositions;
    }
    
    public void setHrNumberOfPositions(int hrNumberOfPositions) {
        this.hrNumberOfPositions = hrNumberOfPositions;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


