package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PolicyGroup generated by hbm2java
 */
public class PolicyGroup  implements java.io.Serializable {


     private int id;
     private String groupCode;
     private String groupName;
     private Integer orgId;
     private Date dateCreated;

    public PolicyGroup() {
    }

	
    public PolicyGroup(int id, String groupCode, String groupName, Date dateCreated) {
        this.id = id;
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.dateCreated = dateCreated;
    }
    public PolicyGroup(int id, String groupCode, String groupName, Integer orgId, Date dateCreated) {
       this.id = id;
       this.groupCode = groupCode;
       this.groupName = groupName;
       this.orgId = orgId;
       this.dateCreated = dateCreated;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


