package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PolicyMda generated by hbm2java
 */
public class PolicyMda  implements java.io.Serializable {


     private int id;
     private Policies policies;
     private Integer mdaId;
     private Integer policyYearId;
     private Date dateCreated;
     private Integer orgId;

    public PolicyMda() {
    }

	
    public PolicyMda(int id) {
        this.id = id;
    }
    public PolicyMda(int id, Policies policies, Integer mdaId, Integer policyYearId, Date dateCreated, Integer orgId) {
       this.id = id;
       this.policies = policies;
       this.mdaId = mdaId;
       this.policyYearId = policyYearId;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Policies getPolicies() {
        return this.policies;
    }
    
    public void setPolicies(Policies policies) {
        this.policies = policies;
    }
    public Integer getMdaId() {
        return this.mdaId;
    }
    
    public void setMdaId(Integer mdaId) {
        this.mdaId = mdaId;
    }
    public Integer getPolicyYearId() {
        return this.policyYearId;
    }
    
    public void setPolicyYearId(Integer policyYearId) {
        this.policyYearId = policyYearId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


