package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Programmes generated by hbm2java
 */
public class Programmes  implements java.io.Serializable {


     private int id;
     private String code;
     private String name;
     private Date datecreated;
     private int orgId;

    public Programmes() {
    }

    public Programmes(int id, String code, String name, Date datecreated, int orgId) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.datecreated = datecreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }




}


