package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProgrammeSegmentHeader2 generated by hbm2java
 */
public class ProgrammeSegmentHeader2  implements java.io.Serializable {


     private int id;
     private String name;
     private String code;
     private int parent;
     private Date dateCreated;
     private Integer orgId;
     private boolean projectStatus;
     private Integer yearId;

    public ProgrammeSegmentHeader2() {
    }

	
    public ProgrammeSegmentHeader2(int id, String name, String code, int parent, Date dateCreated, boolean projectStatus) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.parent = parent;
        this.dateCreated = dateCreated;
        this.projectStatus = projectStatus;
    }
    public ProgrammeSegmentHeader2(int id, String name, String code, int parent, Date dateCreated, Integer orgId, boolean projectStatus, Integer yearId) {
       this.id = id;
       this.name = name;
       this.code = code;
       this.parent = parent;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.projectStatus = projectStatus;
       this.yearId = yearId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public int getParent() {
        return this.parent;
    }
    
    public void setParent(int parent) {
        this.parent = parent;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public boolean isProjectStatus() {
        return this.projectStatus;
    }
    
    public void setProjectStatus(boolean projectStatus) {
        this.projectStatus = projectStatus;
    }
    public Integer getYearId() {
        return this.yearId;
    }
    
    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }




}


