package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProjectDetail generated by hbm2java
 */
public class ProjectDetail  implements java.io.Serializable {


     private int id;
     private int mda;
     private int department;
     private String code;
     private String sectorGoal;
     private String sectorProgramme;
     private int rank;
     private Date dateCreated;
     private Integer orgId;
     private Float score;
     private String name;
     private Integer yearId;
     private Integer projectStatus;
     private String policy;
     private String programme;
     private String objective;
     private String projectCode;
     
    public ProjectDetail() {
    }

	
    public ProjectDetail(int id, int mda, int department, String code, String sectorGoal, String sectorProgramme, int rank) {
        this.id = id;
        this.mda = mda;
        this.department = department;
        this.code = code;
        this.sectorGoal = sectorGoal;
        this.sectorProgramme = sectorProgramme;
        this.rank = rank;
    }
    public ProjectDetail(int id, int mda, int department, String code, String sectorGoal, String sectorProgramme, int rank, Date dateCreated, Integer orgId, Float score, String name, Integer yearId, Integer projectStatus, String policy, String programme, String objective, String projectCode) {
       this.id = id;
       this.mda = mda;
       this.department = department;
       this.code = code;
       this.sectorGoal = sectorGoal;
       this.sectorProgramme = sectorProgramme;
       this.rank = rank;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.score = score;
       this.name = name;
       this.yearId = yearId;
       this.projectStatus = projectStatus;
       this.policy = policy;
       this.programme = programme;
       this.objective = objective;
       this.projectCode = projectCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMda() {
        return this.mda;
    }
    
    public void setMda(int mda) {
        this.mda = mda;
    }
    public int getDepartment() {
        return this.department;
    }
    
    public void setDepartment(int department) {
        this.department = department;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getSectorGoal() {
        return this.sectorGoal;
    }
    
    public void setSectorGoal(String sectorGoal) {
        this.sectorGoal = sectorGoal;
    }
    public String getSectorProgramme() {
        return this.sectorProgramme;
    }
    
    public void setSectorProgramme(String sectorProgramme) {
        this.sectorProgramme = sectorProgramme;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getYearId() {
        return this.yearId;
    }
    
    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }
    public Integer getProjectStatus() {
        return this.projectStatus;
    }
    
    public void setProjectStatus(Integer projectStatus) {
        this.projectStatus = projectStatus;
    }
    public String getPolicy() {
        return this.policy;
    }
    
    public void setPolicy(String policy) {
        this.policy = policy;
    }
    public String getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(String programme) {
        this.programme = programme;
    }
    public String getObjective() {
        return this.objective;
    }
    
    public void setObjective(String objective) {
        this.objective = objective;
    }

    public String getProjectCode() {
        return this.projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    


}


