package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RequestAgents generated by hbm2java
 */
public class RequestAgents  implements java.io.Serializable {


     private int id;
     private Mdas mdas;
     private RequestAgentTypes requestAgentTypes;
     private RequestTypes requestTypes;
     private Roles roles;
     private Date dateCreated;
     private Integer orgId;

    public RequestAgents() {
    }

	
    public RequestAgents(int id, Mdas mdas, RequestAgentTypes requestAgentTypes, RequestTypes requestTypes, Roles roles, Date dateCreated) {
        this.id = id;
        this.mdas = mdas;
        this.requestAgentTypes = requestAgentTypes;
        this.requestTypes = requestTypes;
        this.roles = roles;
        this.dateCreated = dateCreated;
    }
    public RequestAgents(int id, Mdas mdas, RequestAgentTypes requestAgentTypes, RequestTypes requestTypes, Roles roles, Date dateCreated, Integer orgId) {
       this.id = id;
       this.mdas = mdas;
       this.requestAgentTypes = requestAgentTypes;
       this.requestTypes = requestTypes;
       this.roles = roles;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mdas getMdas() {
        return this.mdas;
    }
    
    public void setMdas(Mdas mdas) {
        this.mdas = mdas;
    }
    public RequestAgentTypes getRequestAgentTypes() {
        return this.requestAgentTypes;
    }
    
    public void setRequestAgentTypes(RequestAgentTypes requestAgentTypes) {
        this.requestAgentTypes = requestAgentTypes;
    }
    public RequestTypes getRequestTypes() {
        return this.requestTypes;
    }
    
    public void setRequestTypes(RequestTypes requestTypes) {
        this.requestTypes = requestTypes;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


