package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RequestApprovals generated by hbm2java
 */
public class RequestApprovals  implements java.io.Serializable {


     private int id;
     private RequestDetails requestDetails;
     private Users users;
     private int approvalStatus;
     private String comment;
     private Date dateCreated;
     private int orgId;

    public RequestApprovals() {
    }

    public RequestApprovals(int id, RequestDetails requestDetails, Users users, int approvalStatus, String comment, Date dateCreated, int orgId) {
       this.id = id;
       this.requestDetails = requestDetails;
       this.users = users;
       this.approvalStatus = approvalStatus;
       this.comment = comment;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public RequestDetails getRequestDetails() {
        return this.requestDetails;
    }
    
    public void setRequestDetails(RequestDetails requestDetails) {
        this.requestDetails = requestDetails;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getApprovalStatus() {
        return this.approvalStatus;
    }
    
    public void setApprovalStatus(int approvalStatus) {
        this.approvalStatus = approvalStatus;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }




}


