package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RequestDocuments generated by hbm2java
 */
public class RequestDocuments  implements java.io.Serializable {


     private int id;
     private RequestDetails requestDetails;
     private String documentUrl;
     private String documentText;
     private Date dateCreated;
     private Integer orgId;

    public RequestDocuments() {
    }

	
    public RequestDocuments(int id, RequestDetails requestDetails, Date dateCreated) {
        this.id = id;
        this.requestDetails = requestDetails;
        this.dateCreated = dateCreated;
    }
    public RequestDocuments(int id, RequestDetails requestDetails, String documentUrl, String documentText, Date dateCreated, Integer orgId) {
       this.id = id;
       this.requestDetails = requestDetails;
       this.documentUrl = documentUrl;
       this.documentText = documentText;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public RequestDetails getRequestDetails() {
        return this.requestDetails;
    }
    
    public void setRequestDetails(RequestDetails requestDetails) {
        this.requestDetails = requestDetails;
    }
    public String getDocumentUrl() {
        return this.documentUrl;
    }
    
    public void setDocumentUrl(String documentUrl) {
        this.documentUrl = documentUrl;
    }
    public String getDocumentText() {
        return this.documentText;
    }
    
    public void setDocumentText(String documentText) {
        this.documentText = documentText;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


