package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RequestDetails generated by hbm2java
 */
public class RequestDetails  implements java.io.Serializable {


     private int id;
     private BudgetYears budgetYears;
     private RequestTypes requestTypes;
     private String itemUrl;
     private Integer versionId;
     private boolean requiresApproval;
     private boolean fullyApproved;
     private Date dateCreated;
     private Integer orgId;
     private Set requestDocumentses = new HashSet(0);
     private Set requestApprovalses = new HashSet(0);

    public RequestDetails() {
    }

	
    public RequestDetails(int id, BudgetYears budgetYears, RequestTypes requestTypes, String itemUrl, boolean requiresApproval, boolean fullyApproved, Date dateCreated) {
        this.id = id;
        this.budgetYears = budgetYears;
        this.requestTypes = requestTypes;
        this.itemUrl = itemUrl;
        this.requiresApproval = requiresApproval;
        this.fullyApproved = fullyApproved;
        this.dateCreated = dateCreated;
    }
    public RequestDetails(int id, BudgetYears budgetYears, RequestTypes requestTypes, String itemUrl, Integer versionId, boolean requiresApproval, boolean fullyApproved, Date dateCreated, Integer orgId, Set requestDocumentses, Set requestApprovalses) {
       this.id = id;
       this.budgetYears = budgetYears;
       this.requestTypes = requestTypes;
       this.itemUrl = itemUrl;
       this.versionId = versionId;
       this.requiresApproval = requiresApproval;
       this.fullyApproved = fullyApproved;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.requestDocumentses = requestDocumentses;
       this.requestApprovalses = requestApprovalses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BudgetYears getBudgetYears() {
        return this.budgetYears;
    }
    
    public void setBudgetYears(BudgetYears budgetYears) {
        this.budgetYears = budgetYears;
    }
    public RequestTypes getRequestTypes() {
        return this.requestTypes;
    }
    
    public void setRequestTypes(RequestTypes requestTypes) {
        this.requestTypes = requestTypes;
    }
    public String getItemUrl() {
        return this.itemUrl;
    }
    
    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl;
    }
    public Integer getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }
    public boolean isRequiresApproval() {
        return this.requiresApproval;
    }
    
    public void setRequiresApproval(boolean requiresApproval) {
        this.requiresApproval = requiresApproval;
    }
    public boolean isFullyApproved() {
        return this.fullyApproved;
    }
    
    public void setFullyApproved(boolean fullyApproved) {
        this.fullyApproved = fullyApproved;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Set getRequestDocumentses() {
        return this.requestDocumentses;
    }
    
    public void setRequestDocumentses(Set requestDocumentses) {
        this.requestDocumentses = requestDocumentses;
    }
    public Set getRequestApprovalses() {
        return this.requestApprovalses;
    }
    
    public void setRequestApprovalses(Set requestApprovalses) {
        this.requestApprovalses = requestApprovalses;
    }




}


