package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SapPersonnel generated by hbm2java
 */
public class SapPersonnel  implements java.io.Serializable {


     private int id;
     private String mandt;
     private String fiscalYear;
     private String repDate;
     private String repTime;
     private String adminSegment;
     private String mdaOrgId;
     private String mdaName;
     private String deptUnitId;
     private String deptUnitName;
     private String costCenter;
     private String posJobId;
     private String posJobName;
     private String salGrade;
     private Double hcCurrent;
     private Double hcNext;
     private Double amtCurrent;
     private Double amtNext;
     private Double basicCurrent;
     private Double transportCurrent;
     private Double rentCurrent;
     private Double bonusCurrent;
     private Double othersCurrent;
     private Double basicNext;
     private Double transportNext;
     private Double rentNext;
     private Double bonusNext;
     private Double othersNext;
     private Date dateCreated;
     private Integer orgId;

    public SapPersonnel() {
    }

	
    public SapPersonnel(int id) {
        this.id = id;
    }
    public SapPersonnel(int id, String mandt, String fiscalYear, String repDate, String repTime, String adminSegment, String mdaOrgId, String mdaName, String deptUnitId, String deptUnitName, String costCenter, String posJobId, String posJobName, String salGrade, Double hcCurrent, Double hcNext, Double amtCurrent, Double amtNext, Double basicCurrent, Double transportCurrent, Double rentCurrent, Double bonusCurrent, Double othersCurrent, Double basicNext, Double transportNext, Double rentNext, Double bonusNext, Double othersNext, Date dateCreated, Integer orgId) {
       this.id = id;
       this.mandt = mandt;
       this.fiscalYear = fiscalYear;
       this.repDate = repDate;
       this.repTime = repTime;
       this.adminSegment = adminSegment;
       this.mdaOrgId = mdaOrgId;
       this.mdaName = mdaName;
       this.deptUnitId = deptUnitId;
       this.deptUnitName = deptUnitName;
       this.costCenter = costCenter;
       this.posJobId = posJobId;
       this.posJobName = posJobName;
       this.salGrade = salGrade;
       this.hcCurrent = hcCurrent;
       this.hcNext = hcNext;
       this.amtCurrent = amtCurrent;
       this.amtNext = amtNext;
       this.basicCurrent = basicCurrent;
       this.transportCurrent = transportCurrent;
       this.rentCurrent = rentCurrent;
       this.bonusCurrent = bonusCurrent;
       this.othersCurrent = othersCurrent;
       this.basicNext = basicNext;
       this.transportNext = transportNext;
       this.rentNext = rentNext;
       this.bonusNext = bonusNext;
       this.othersNext = othersNext;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMandt() {
        return this.mandt;
    }
    
    public void setMandt(String mandt) {
        this.mandt = mandt;
    }
    public String getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }
    public String getRepDate() {
        return this.repDate;
    }
    
    public void setRepDate(String repDate) {
        this.repDate = repDate;
    }
    public String getRepTime() {
        return this.repTime;
    }
    
    public void setRepTime(String repTime) {
        this.repTime = repTime;
    }
    public String getAdminSegment() {
        return this.adminSegment;
    }
    
    public void setAdminSegment(String adminSegment) {
        this.adminSegment = adminSegment;
    }
    public String getMdaOrgId() {
        return this.mdaOrgId;
    }
    
    public void setMdaOrgId(String mdaOrgId) {
        this.mdaOrgId = mdaOrgId;
    }
    public String getMdaName() {
        return this.mdaName;
    }
    
    public void setMdaName(String mdaName) {
        this.mdaName = mdaName;
    }
    public String getDeptUnitId() {
        return this.deptUnitId;
    }
    
    public void setDeptUnitId(String deptUnitId) {
        this.deptUnitId = deptUnitId;
    }
    public String getDeptUnitName() {
        return this.deptUnitName;
    }
    
    public void setDeptUnitName(String deptUnitName) {
        this.deptUnitName = deptUnitName;
    }
    public String getCostCenter() {
        return this.costCenter;
    }
    
    public void setCostCenter(String costCenter) {
        this.costCenter = costCenter;
    }
    public String getPosJobId() {
        return this.posJobId;
    }
    
    public void setPosJobId(String posJobId) {
        this.posJobId = posJobId;
    }
    public String getPosJobName() {
        return this.posJobName;
    }
    
    public void setPosJobName(String posJobName) {
        this.posJobName = posJobName;
    }
    public String getSalGrade() {
        return this.salGrade;
    }
    
    public void setSalGrade(String salGrade) {
        this.salGrade = salGrade;
    }
    public Double getHcCurrent() {
        return this.hcCurrent;
    }
    
    public void setHcCurrent(Double hcCurrent) {
        this.hcCurrent = hcCurrent;
    }
    public Double getHcNext() {
        return this.hcNext;
    }
    
    public void setHcNext(Double hcNext) {
        this.hcNext = hcNext;
    }
    public Double getAmtCurrent() {
        return this.amtCurrent;
    }
    
    public void setAmtCurrent(Double amtCurrent) {
        this.amtCurrent = amtCurrent;
    }
    public Double getAmtNext() {
        return this.amtNext;
    }
    
    public void setAmtNext(Double amtNext) {
        this.amtNext = amtNext;
    }
    public Double getBasicCurrent() {
        return this.basicCurrent;
    }
    
    public void setBasicCurrent(Double basicCurrent) {
        this.basicCurrent = basicCurrent;
    }
    public Double getTransportCurrent() {
        return this.transportCurrent;
    }
    
    public void setTransportCurrent(Double transportCurrent) {
        this.transportCurrent = transportCurrent;
    }
    public Double getRentCurrent() {
        return this.rentCurrent;
    }
    
    public void setRentCurrent(Double rentCurrent) {
        this.rentCurrent = rentCurrent;
    }
    public Double getBonusCurrent() {
        return this.bonusCurrent;
    }
    
    public void setBonusCurrent(Double bonusCurrent) {
        this.bonusCurrent = bonusCurrent;
    }
    public Double getOthersCurrent() {
        return this.othersCurrent;
    }
    
    public void setOthersCurrent(Double othersCurrent) {
        this.othersCurrent = othersCurrent;
    }
    public Double getBasicNext() {
        return this.basicNext;
    }
    
    public void setBasicNext(Double basicNext) {
        this.basicNext = basicNext;
    }
    public Double getTransportNext() {
        return this.transportNext;
    }
    
    public void setTransportNext(Double transportNext) {
        this.transportNext = transportNext;
    }
    public Double getRentNext() {
        return this.rentNext;
    }
    
    public void setRentNext(Double rentNext) {
        this.rentNext = rentNext;
    }
    public Double getBonusNext() {
        return this.bonusNext;
    }
    
    public void setBonusNext(Double bonusNext) {
        this.bonusNext = bonusNext;
    }
    public Double getOthersNext() {
        return this.othersNext;
    }
    
    public void setOthersNext(Double othersNext) {
        this.othersNext = othersNext;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


