package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Scoring generated by hbm2java
 */
public class Scoring  implements java.io.Serializable {


     private int id;
     private String projectCode;
     private Integer projectYear;
     private int criteriaId;
     private Double score;
     private Date dateCreated;
     private Integer orgId;

    public Scoring() {
    }

	
    public Scoring(int id, String projectCode, int criteriaId) {
        this.id = id;
        this.projectCode = projectCode;
        this.criteriaId = criteriaId;
    }
    public Scoring(int id, String projectCode, Integer projectYear, int criteriaId, Double score, Date dateCreated, Integer orgId) {
       this.id = id;
       this.projectCode = projectCode;
       this.projectYear = projectYear;
       this.criteriaId = criteriaId;
       this.score = score;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }
    public Integer getProjectYear() {
        return this.projectYear;
    }
    
    public void setProjectYear(Integer projectYear) {
        this.projectYear = projectYear;
    }
    public int getCriteriaId() {
        return this.criteriaId;
    }
    
    public void setCriteriaId(int criteriaId) {
        this.criteriaId = criteriaId;
    }
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


