package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sectors generated by hbm2java
 */
public class Sectors  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private Double sectorWeight;
     private String sectorCode;

    public Sectors() {
    }

	
    public Sectors(int id, String name, Date dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public Sectors(int id, String name, Date dateCreated, Integer orgId, Double sectorWeight, String sectorCode) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.sectorWeight = sectorWeight;
       this.sectorCode = sectorCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Double getSectorWeight() {
        return this.sectorWeight;
    }
    
    public void setSectorWeight(Double sectorWeight) {
        this.sectorWeight = sectorWeight;
    }
    public String getSectorCode() {
        return this.sectorCode;
    }
    
    public void setSectorCode(String sectorCode) {
        this.sectorCode = sectorCode;
    }




}


