package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SegmentsSettings generated by hbm2java
 */
public class SegmentsSettings  implements java.io.Serializable {


     private int id;
     private String segmentName;
     private Integer orgId;
     private Date dateCreated;
     private Integer codeLenght;

    public SegmentsSettings() {
    }

	
    public SegmentsSettings(int id) {
        this.id = id;
    }
    public SegmentsSettings(int id, String segmentName, Integer orgId, Date dateCreated, Integer codeLenght) {
       this.id = id;
       this.segmentName = segmentName;
       this.orgId = orgId;
       this.dateCreated = dateCreated;
       this.codeLenght = codeLenght;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSegmentName() {
        return this.segmentName;
    }
    
    public void setSegmentName(String segmentName) {
        this.segmentName = segmentName;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getCodeLenght() {
        return this.codeLenght;
    }
    
    public void setCodeLenght(Integer codeLenght) {
        this.codeLenght = codeLenght;
    }




}


