package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SubSectors generated by hbm2java
 */
public class SubSectors  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private Double subSectorWeight;
     private String subSectorCode;
     private Integer sectorId;

    public SubSectors() {
    }

	
    public SubSectors(int id, Date dateCreated) {
        this.id = id;
        this.dateCreated = dateCreated;
    }
    public SubSectors(int id, String name, Date dateCreated, Integer orgId, Double subSectorWeight, String subSectorCode, Integer sectorId) {
       this.id = id;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.subSectorWeight = subSectorWeight;
       this.subSectorCode = subSectorCode;
       this.sectorId = sectorId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Double getSubSectorWeight() {
        return this.subSectorWeight;
    }
    
    public void setSubSectorWeight(Double subSectorWeight) {
        this.subSectorWeight = subSectorWeight;
    }
    public String getSubSectorCode() {
        return this.subSectorCode;
    }
    
    public void setSubSectorCode(String subSectorCode) {
        this.subSectorCode = subSectorCode;
    }
    public Integer getSectorId() {
        return this.sectorId;
    }
    
    public void setSectorId(Integer sectorId) {
        this.sectorId = sectorId;
    }




}


