package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SystemMenu generated by hbm2java
 */
public class SystemMenu  implements java.io.Serializable {


     private int id;
     private MenuCategory menuCategory;
     private String name;
     private Date dateCreated;
     private Integer orgId;
     private String menuUrl;
     private Integer rank;
     private Set menuUsers = new HashSet(0);
     private Set menuRoles = new HashSet(0);

    public SystemMenu() {
    }

	
    public SystemMenu(int id, MenuCategory menuCategory, String name, Date dateCreated) {
        this.id = id;
        this.menuCategory = menuCategory;
        this.name = name;
        this.dateCreated = dateCreated;
    }
    public SystemMenu(int id, MenuCategory menuCategory, String name, Date dateCreated, Integer orgId, String menuUrl, Integer rank, Set menuUsers, Set menuRoles) {
       this.id = id;
       this.menuCategory = menuCategory;
       this.name = name;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.menuUrl = menuUrl;
       this.rank = rank;
       this.menuUsers = menuUsers;
       this.menuRoles = menuRoles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MenuCategory getMenuCategory() {
        return this.menuCategory;
    }
    
    public void setMenuCategory(MenuCategory menuCategory) {
        this.menuCategory = menuCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
    public Set getMenuUsers() {
        return this.menuUsers;
    }
    
    public void setMenuUsers(Set menuUsers) {
        this.menuUsers = menuUsers;
    }
    public Set getMenuRoles() {
        return this.menuRoles;
    }
    
    public void setMenuRoles(Set menuRoles) {
        this.menuRoles = menuRoles;
    }




}


