package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private Users users;
     private Date dateCreated;
     private Integer orgId;

    public UserRole() {
    }

	
    public UserRole(int id, Roles roles, Users users, Date dateCreated) {
        this.id = id;
        this.roles = roles;
        this.users = users;
        this.dateCreated = dateCreated;
    }
    public UserRole(int id, Roles roles, Users users, Date dateCreated, Integer orgId) {
       this.id = id;
       this.roles = roles;
       this.users = users;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


