package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * YearBudgetVersions generated by hbm2java
 */
public class YearBudgetVersions  implements java.io.Serializable {


     private int id;
     private Integer budgetYearId;
     private String yearBudgetVersion;
     private Date dateCreated;
     private Integer orgId;
     private Integer status;

    public YearBudgetVersions() {
    }

	
    public YearBudgetVersions(int id) {
        this.id = id;
    }
    public YearBudgetVersions(int id, Integer budgetYearId, String yearBudgetVersion, Date dateCreated, Integer orgId, Integer status) {
       this.id = id;
       this.budgetYearId = budgetYearId;
       this.yearBudgetVersion = yearBudgetVersion;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getBudgetYearId() {
        return this.budgetYearId;
    }
    
    public void setBudgetYearId(Integer budgetYearId) {
        this.budgetYearId = budgetYearId;
    }
    public String getYearBudgetVersion() {
        return this.yearBudgetVersion;
    }
    
    public void setYearBudgetVersion(String yearBudgetVersion) {
        this.yearBudgetVersion = yearBudgetVersion;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


