package com.bpp.hibernate;
// Generated Aug 14, 2018 4:15:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * YearBudgetTypes generated by hbm2java
 */
public class YearBudgetTypes  implements java.io.Serializable {


     private int id;
     private String budgetType;
     private String sapBudgetType;
     private Date dateCreated;
     private Integer orgId;

    public YearBudgetTypes() {
    }

	
    public YearBudgetTypes(int id) {
        this.id = id;
    }
    public YearBudgetTypes(int id, String budgetType, String sapBudgetType, Date dateCreated, Integer orgId) {
       this.id = id;
       this.budgetType = budgetType;
       this.sapBudgetType = sapBudgetType;
       this.dateCreated = dateCreated;
       this.orgId = orgId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getBudgetType() {
        return this.budgetType;
    }
    
    public void setBudgetType(String budgetType) {
        this.budgetType = budgetType;
    }
    public String getSapBudgetType() {
        return this.sapBudgetType;
    }
    
    public void setSapBudgetType(String sapBudgetType) {
        this.sapBudgetType = sapBudgetType;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


